POST http://localhost:8080/
Content-Type: application/json

{
  "name": "asdfasd!",
  "author": "Poshjasfdasdin"
}
###
GET http://localhost:8080/book/all

###

POST http://localhost:8080/author
Content-Type: application/json

{
  "firstName": "asdfasdf!",
  "lastName": "qwerqwe",
  "middleName": "12234",
  "isAlive": true
}
###

GET http://localhost:8080/author/55

###

POST http://localhost:8080/cabinet
Content-Type: application/json

{
  "numOfRack": 12
}
###

GET http://localhost:8080/cabinet/all

